substitutions:
  name: airthings_status

esphome:
  name: ${name}
  platform: ESP32
  board: nodemcu-32s

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base.yaml

# Airthings BLE
esp32_ble_tracker:

ble_client:
  - mac_address: !secret airthings_basement_mac
    id: airthings_basement

sensor:
  - platform: airthings_wave_plus
    ble_client_id: airthings_basement
    update_interval: 5min # default
    temperature:
      name: "Airthings Basement Temperature"
      unit_of_measurement: "°F"
      accuracy_decimals: 1
      filters:
        - lambda: return x * (9.0/5.0) + 32.0; # convert to °F
      on_value_range:
        - below: 60
          then:
            - light.turn_on:
                id: led5
                effect: none
                brightness: 16%
                red: 100%
                green: 0%
                blue: 100%
        - above: 61
          below: 68
          then:
            - light.turn_on:
                id: led5
                effect: none
                brightness: 16%
                red: 0%
                green: 0%
                blue: 100%
        - above: 69
          below: 77
          then:
            - light.turn_on:
                id: led5
                effect: none
                brightness: 16%
                red: 0%
                green: 100%
                blue: 0%
        - above: 78
          below: 85
          then:
            - light.turn_on:
                id: led5
                effect: none
                brightness: 16%
                red: 100%
                green: 70%
                blue: 0%
        - above: 86
          then:
            - light.turn_on:
                id: led5
                effect: none
                brightness: 16%
                red: 100%
                green: 0%
                blue: 0%
    radon:
      name: "Airthings Basement Radon 1 Day Avg"
      unit_of_measurement: "pCi/L"
      accuracy_decimals: 1
      filters:
        - lambda: return x / 37.0; # convert to pCi/L from Bq/m^3
      on_value_range:
        - above: 0
          below: 2.7
          then:
            - light.turn_on:
                id: led1
                effect: none
                brightness: 16%
                red: 0%
                green: 100%
                blue: 0%
        - above: 2.7
          below: 4.0
          then:
            - light.turn_on:
                id: led1
                effect: none
                brightness: 16%
                red: 100%
                green: 100%
                blue: 0%
        - above: 4.0
          below: 8.0
          then:
            - light.turn_on:
                id: led1
                effect: none
                brightness: 16%
                red: 100%
                green: 0%
                blue: 0%
        - above: 8.0
          then:
            - light.turn_on:
                id: led1
                effect: Red Flash
    radon_long_term:
      name: "Airthings Basement Radon LongTerm Avg"
      unit_of_measurement: "pCi/L"
      accuracy_decimals: 1
      filters:
        - lambda: return x / 37.0; # convert to pCi/L from Bq/m^3
    pressure:
      name: "Airthings Basement Pressure"
      on_value_range:
        - below: 500
          then:
            - light.turn_on:
                id: led6
                effect: Red Flash
        - above: 501
          below: 800
          then:
            - light.turn_on:
                id: led6
                effect: none
                brightness: 16%
                red: 100%
                green: 70%
                blue: 0%
        - above: 501
          below: 800
          then:
            - light.turn_on:
                id: led6
                effect: none
                brightness: 16%
                red: 100%
                green: 70%
                blue: 0%
        - above: 801
          below: 1000
          then:
            - light.turn_on:
                id: led6
                effect: none
                brightness: 16%
                red: 0%
                green: 100%
                blue: 0%
        - above: 1001
          then:
            - light.turn_on:
                id: led6
                effect: none
                brightness: 16%
                red: 0%
                green: 100%
                blue: 100%
    humidity:
      name: "Airthings Basement Humidity"
      on_value_range:
        - above: 0
          below: 15
          then:
            - light.turn_on:
                id: led4
                effect: none
                brightness: 16%
                red: 100%
                green: 0%
                blue: 0%
        - above: 16
          below: 30
          then:
            - light.turn_on:
                id: led4
                effect: none
                brightness: 16%
                red: 100%
                green: 100%
                blue: 0%
        - above: 31
          below: 60
          then:
            - light.turn_on:
                id: led4
                effect: none
                brightness: 16%
                red: 0%
                green: 100%
                blue: 0%
        - above: 61
          below: 80
          then:
            - light.turn_on:
                id: led4
                effect: none
                brightness: 16%
                red: 0%
                green: 0%
                blue: 100%
        - above: 81
          below: 100
          then:
            - light.turn_on:
                id: led4
                effect: none
                brightness: 16%
                red: 100%
                green: 0%
                blue: 100%
    co2:
      name: "Airthings Basement CO2"
      on_value_range:
        - above: 0
          below: 400
          then:
            - light.turn_on:
                id: led3
                effect: none
                brightness: 16%
                red: 0%
                green: 0%
                blue: 100%
        - above: 401
          below: 600
          then:
            - light.turn_on:
                id: led3
                effect: none
                brightness: 16%
                red: 0%
                green: 100%
                blue: 0%
        - above: 601
          below: 800
          then:
            - light.turn_on:
                id: led3
                effect: none
                brightness: 16%
                red: 100%
                green: 100%
                blue: 0%
        - above: 801
          below: 1200
          then:
            - light.turn_on:
                id: led3
                effect: none
                brightness: 16%
                red: 100%
                green: 60%
                blue: 0%
        - above: 1201
          below: 2000
          then:
            - light.turn_on:
                id: led3
                effect: none
                brightness: 16%
                red: 100%
                green: 60%
                blue: 0%
        - above: 2001
          then:
            - light.turn_on:
                id: led3
                effect: Red Flash
    tvoc:
      name: "Airthings Basement VOC"
      on_value_range:
        - above: 0
          below: 100
          then:
            - light.turn_on:
                id: led2
                effect: none
                brightness: 16%
                red: 0%
                green: 100%
                blue: 0%
        - above: 101
          below: 200
          then:
            - light.turn_on:
                id: led2
                effect: none
                brightness: 16%
                red: 100%
                green: 100%
                blue: 0%
        - above: 201
          below: 400
          then:
            - light.turn_on:
                id: led2
                effect: none
                brightness: 16%
                red: 100%
                green: 70%
                blue: 0%
        - above: 401
          below: 700
          then:
            - light.turn_on:
                id: led2
                effect: none
                brightness: 16%
                red: 100%
                green: 30%
                blue: 0%
        - above: 701
          below: 1000
          then:
            - light.turn_on:
                id: led2
                effect: none
                brightness: 16%
                red: 100%
                green: 0%
                blue: 0%
        - above: 1001
          then:
            - light.turn_on:
                id: led2
                effect: Red Flash

light:
  - platform: fastled_clockless
    id: leds
    chipset: WS2812B
    pin: GPIO13
    num_leds: 7
    rgb_order: GRB
    default_transition_length: 0s
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: partition
    id: led0
    segments:
      - id: leds
        from: 0
        to: 0
    default_transition_length: 0s
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: partition
    id: led1
    segments:
      - id: leds
        from: 1
        to: 1
    default_transition_length: 0s
    restore_mode: RESTORE_DEFAULT_OFF
    effects:
      - automation:
          name: "Red Flash"
          sequence:
            - light.turn_on:
                id: led1
                brightness: 16%
                red: 100%
                green: 0%
                blue: 0%
            - delay: 1000ms
            - light.turn_on:
                id: led1
                brightness: 0%
                red: 100%
                green: 0%
                blue: 0%
            - delay: 1000 ms
  - platform: partition
    id: led2
    segments:
      - id: leds
        from: 2
        to: 2
    default_transition_length: 0s
    restore_mode: RESTORE_DEFAULT_OFF
    effects:
      - automation:
          name: "Red Flash"
          sequence:
            - light.turn_on:
                id: led2
                brightness: 16%
                red: 100%
                green: 0%
                blue: 0%
            - delay: 1000ms
            - light.turn_on:
                id: led2
                brightness: 0%
                red: 100%
                green: 0%
                blue: 0%
            - delay: 1000 ms
  - platform: partition
    id: led3
    segments:
      - id: leds
        from: 3
        to: 3
    default_transition_length: 0s
    restore_mode: RESTORE_DEFAULT_OFF
    effects:
      - automation:
          name: "Red Flash"
          sequence:
            - light.turn_on:
                id: led3
                brightness: 16%
                red: 100%
                green: 0%
                blue: 0%
            - delay: 1000ms
            - light.turn_on:
                id: led3
                brightness: 0%
                red: 100%
                green: 0%
                blue: 0%
            - delay: 1000 ms
  - platform: partition
    id: led4
    segments:
      - id: leds
        from: 4
        to: 4
    default_transition_length: 0s
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: partition
    id: led5
    segments:
      - id: leds
        from: 5
        to: 5
    default_transition_length: 0s
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: partition
    id: led6
    segments:
      - id: leds
        from: 6
        to: 6
    default_transition_length: 0s
    restore_mode: RESTORE_DEFAULT_OFF
    effects:
      - automation:
          name: "Red Flash"
          sequence:
            - light.turn_on:
                id: led6
                brightness: 16%
                red: 100%
                green: 0%
                blue: 0%
            - delay: 1000ms
            - light.turn_on:
                id: led6
                brightness: 0%
                red: 100%
                green: 0%
                blue: 0%
            - delay: 1000 ms