# BT Proxy using WT32-ETH01 module
substitutions:
  name: bluetooth_proxy_01

esphome:
  name: ${name}
  min_version: 2024.6.0
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: wt32-eth01
  framework:
    type: esp-idf

packages:
  device_base: !include common/device_base.yaml

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16
  domain: !secret wifi_domain

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

button:
  - platform: safe_mode
    id: button_safe_mode
    name: ${name} Safe Mode Boot

  - platform: factory_reset
    id: factory_reset_btn
    name: ${name} Factory reset
    