# BT Proxy using WT32-ETH01 module
# some hardware info: https://github.com/egnor/wt32-eth01?tab=readme-ov-file
# esphome blueprint: https://github.com/esphome/bluetooth-proxies/blob/main/wt32/wt32-eth01.yaml
substitutions:
  name: bluetooth-proxy-01
  id_prefix: bluetooth_proxy_01
  friendly_name: "Bluetooth Proxy 01"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: wt32-eth01
  framework:
    type: esp-idf

packages:
  device_base: !include common/device_base.yaml
  chip_temp: !include common/chip_temp.yaml

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16
  domain: !secret wifi_domain

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true
