substitutions:
  name: brew_sign

esphome:
  name: ${name}
  platform: ESP8266
  board: esp01_1m

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base.yaml

# Example configuration entry
light:
  - platform: monochromatic
    name: "Brew Sign"
    output: light_output
    effects:
      - pulse:
          name: "Pulse"
          transition_length: 1.0s      # defaults to 1s
          update_interval: 1.0s
      - pulse:
          name: "Flash"
          transition_length: 0.0s      # defaults to 1s
          update_interval: 1.0s
      - random:
          name: "Random"
          transition_length: 3s
          update_interval: 5s
      - flicker:
          name: "Flicker"
          alpha: 95%
          intensity: 5.0%

output:
  - platform: esp8266_pwm
    pin: GPIO2
    frequency: 1000 Hz
    id: light_output
    min_power: 0.06
    max_power: 1.00
    zero_means_zero: true
