substitutions:
  name: brew-sign
  id_prefix: brew_sign
  friendly_name: "Brew Sign"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp8266:
  board: esp01_1m

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base.yaml

# Example configuration entry
light:
  - platform: monochromatic
    name: ${friendly_name}
    id: ${id_prefix}
    output: ${id_prefix}_light_output
    effects:
      - pulse:
          name: "Pulse"
          transition_length: 1.0s      # defaults to 1s
          update_interval: 1.0s
      - pulse:
          name: "Flash"
          transition_length: 0.0s      # defaults to 1s
          update_interval: 1.0s
      - random:
          name: "Random"
          transition_length: 3s
          update_interval: 5s
      - flicker:
          name: "Flicker"
          alpha: 95%
          intensity: 5.0%

output:
  - platform: esp8266_pwm
    pin: GPIO2
    frequency: 1000 Hz
    id: ${id_prefix}_light_output
    min_power: 0.005
    max_power: 1.00
    zero_means_zero: true
