substitutions:
  name: drying-oven
  id_prefix: drying_oven
  friendly_name: "Drying Oven"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp8266:
  board: d1_mini
  restore_from_flash: false # dont restore state, so oven is always off after reboot

packages:
  wifi: !include common/wifi.yaml
  web_server: !include common/web_server.yaml
  device_base: !include common/device_base.yaml
  esp8266vcc_adc: !include common/esp8266vcc_adc.yaml

one_wire:
 - platform: gpio
   pin: D3

sensor:
  - platform: dallas_temp
    address: 0xb6000005fd072928
    resolution: 10 # 0.25 deg C
    id: ${id_prefix}_temperature_sensor
    update_interval: 0.2 s
    device_class: ""

  - platform: pid
    name: "Heater Power"
    id: ${id_prefix}_heater_power
    type: HEAT

output:
  - platform: esp8266_pwm
    pin: D2
    frequency: 10 Hz
    id: ${id_prefix}_heater
    power_supply: fan

# hacky way to turn on fan with heater
power_supply:
  - id: fan
    pin: D1
    enable_time: 10s
    keep_on_time: 120s

# button:
#   - platform: template
#     name: "PID Climate Autotune"
#     on_press:
#       - climate.pid.autotune: ${id_prefix}_thermostat

climate:
  - platform: pid
    name: Thermostat
    id: ${id_prefix}_thermostat
    entity_category: ""
    sensor: ${id_prefix}_temperature_sensor
    default_target_temperature: 0°C
    heat_output: ${id_prefix}_heater
    control_parameters: # okay tuning, still have some oscillations and offset (both <1 degC)
      kp: 5
      ki: 0.5
      kd: 25
      min_integral: -2
      max_integral: 2
      output_averaging_samples: 5
    visual:
      min_temperature: 10
      max_temperature: 80
      temperature_step:
        target_temperature: 0.5
        current_temperature: 0.1
