substitutions:
  name: esw01_1

esphome:
  name: ${name}
  platform: ESP8266
  board: esp12e

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base.yaml
  esw01_base: !include common/esw01_base.yaml
