# https://github.com/RATGDO/esphome-ratgdo/blob/main/static/v25iboard.yaml

substitutions:
  id_prefix: garage_door_01
  name: garage-door-01
  friendly_name: "Garage Door 01"
  uart_tx_pin: D1
  uart_rx_pin: D2
  input_obst_pin: D7
  status_door_pin: D0
  status_obstruction_pin: D8
  dry_contact_open_pin: D5
  dry_contact_close_pin: D6
  dry_contact_light_pin: D3

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  project:
    name: ratgdo.v25iboard_secplus2
    version: "2.5i"

esp8266:
  board: d1_mini
  restore_from_flash: true

dashboard_import:
  package_import_url: github://ratgdo/esphome-ratgdo/v25iboard.yaml@main

packages:
  remote_package:
    url: https://github.com/ratgdo/esphome-ratgdo
    files: [base.yaml]
    refresh: 1s
  wifi: !include common/wifi.yaml
  web_server: !include common/web_server.yaml
  esp8266vcc_adc: !include common/esp8266vcc_adc.yaml

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

improv_serial:

# moved device base items here since conflict with the ota components from ratgdo

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret garage_door_01_encryption_key

ota:
  - platform: esphome
    password: !secret static_ota_password

sensor:
  - platform: uptime
    name: "Uptime"
    id: ${id_prefix}_uptime

text_sensor:
  - platform: version
    name: "ESPHome Version"
    id: ${id_prefix}_esphome_version

button:
  - platform: restart
    name: "Restart Node"
    id: ${id_prefix}_restart_button
    disabled_by_default: True
    icon: "mdi:restart"

  - platform: safe_mode
    name: "Restart Node (Safe Mode)"
    id: ${id_prefix}_restart_safe_mode
    disabled_by_default: True
