# https://github.com/ratgdo/esphome-ratgdo/blob/f9590d94ade2792f3dbba9c5ebe7f328a0b43981/static/v25iboard_secplusv1.yaml

substitutions:
  id_prefix: garage_door
  name: garage-door
  friendly_name: "Garage Door"
  uart_tx_pin: D1
  uart_rx_pin: D2
  input_obst_pin: D7
  status_door_pin: D0
  status_obstruction_pin: D8
  dry_contact_open_pin: D5
  dry_contact_close_pin: D6
  dry_contact_light_pin: D3

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  project:
    name: ratgdo.esphome
    version: "2.5i"

esp8266:
  board: d1_mini
  restore_from_flash: true

dashboard_import:
  package_import_url: github://ratgdo/esphome-ratgdo/v25iboard_secplusv1.yaml@main

packages:
  remote_package:
    url: https://github.com/ratgdo/esphome-ratgdo
    files: [base_secplusv1.yaml]
    refresh: 1s
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base.yaml
  web_server: !include common/web_server.yaml

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

improv_serial:
