substitutions:
  name: rf_gateway

esphome:
  name: ${name}
  platform: ESP32
  board: nodemcu-32s

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base.yaml

# Status LED
light:
  - platform: status_led
    id: onboard_led
    pin: GPIO2

remote_transmitter:
  pin: GPIO23
  carrier_duty_percent: 100%
  id: tx_315

# Airthings BLE
esp32_ble_tracker:

ble_client:
  - mac_address: !secret airthings_basement_mac
    id: airthings_basement

sensor:
  - platform: airthings_wave_plus
    ble_client_id: airthings_basement
    update_interval: 5min # default
    temperature:
      name: "Airthings WavePlus Basement Temperature"
      unit_of_measurement: "°F"
      accuracy_decimals: 1
      filters:
        - lambda: return x * (9.0/5.0) + 32.0; # convert to °F
    radon:
      name: "Airthings WavePlus Basement Radon"
      unit_of_measurement: "pCi/L"
      accuracy_decimals: 1
      filters:
        - lambda: return x / 37.0; # convert to pCi/L from Bq/m^3
    radon_long_term:
      name: "Airthings WavePlus Basement Radon Long Term"
      unit_of_measurement: "pCi/L"
      accuracy_decimals: 1
      filters:
        - lambda: return x / 37.0; # convert to pCi/L from Bq/m^3
    pressure:
      name: "Airthings WavePlus Basement Pressure"
    humidity:
      name: "Airthings WavePlus Basement Humidity"
    co2:
      name: "Airthings WavePlus Basement CO2"
    tvoc:
      name: "Airthings WavePlus Basement VOC"

# Individual switches
switch:
# https://www.homedepot.com/p/Defiant-Wireless-Indoor-Outdoor-Remote-Control-with-3-RCV-YLT-42-3/301844754
  - platform: template
    name: "Defiant Outlet 1"
    optimistic: true
    assumed_state: true
    turn_on_action:
      - light.turn_on: onboard_led
      - remote_transmitter.transmit_raw:
          transmitter_id: tx_315
          repeat:
            times: 10
            wait_time: 6ms
          code: [609,-224,224,-609,609,-224,224,-609,609,-224,609,-224,609,-224,224,-609,224,-609,609,-224,609,-224,224,-609,224,-609,609,-224,609,-224,224,-609,224,-609,609,-224,609,-224,609,-224,224,-609,224,-609,224,-609,609,-224,224]
      - light.turn_off: onboard_led
    turn_off_action:
      - light.turn_on: onboard_led
      - remote_transmitter.transmit_raw:
          transmitter_id: tx_315
          repeat:
            times: 10
            wait_time: 6ms
          code: [609,-224,224,-609,609,-224,224,-609,609,-224,609,-224,609,-224,224,-609,224,-609,609,-224,609,-224,224,-609,224,-609,609,-224,609,-224,224,-609,224,-609,609,-224,609,-224,609,-224,609,-224,224,-609,224,-609,224,-609,224]
      - light.turn_off: onboard_led
  - platform: template
    name: "Defiant Outlet 2"
    optimistic: true
    assumed_state: true
    turn_on_action:
      - light.turn_on: onboard_led
      - remote_transmitter.transmit_raw:
          transmitter_id: tx_315
          repeat:
            times: 10
            wait_time: 6ms
          code: [609,-224,224,-609,609,-224,224,-609,609,-224,609,-224,609,-224,224,-609,224,-609,609,-224,609,-224,224,-609,224,-609,609,-224,609,-224,224,-609,224,-609,609,-224,609,-224,609,-224,224,-609,224,-609,609,-224,224,-609,224]
      - light.turn_off: onboard_led
    turn_off_action:
      - light.turn_on: onboard_led
      - remote_transmitter.transmit_raw:
          transmitter_id: tx_315
          repeat:
            times: 10
            wait_time: 6ms
          code: [609,-224,224,-609,609,-224,224,-609,609,-224,609,-224,609,-224,224,-609,224,-609,609,-224,609,-224,224,-609,224,-609,609,-224,609,-224,224,-609,224,-609,609,-224,609,-224,609,-224,224,-609,609,-224,609,-224,224,-609,224]
      - light.turn_off: onboard_led
  - platform: template
    name: "Defiant Outlet 3"
    optimistic: true
    assumed_state: true
    turn_on_action:
      - light.turn_on: onboard_led
      - remote_transmitter.transmit_raw:
          transmitter_id: tx_315
          repeat:
            times: 10
            wait_time: 6ms
          code: [609,-224,224,-609,609,-224,224,-609,609,-224,609,-224,609,-224,224,-609,224,-609,609,-224,609,-224,224,-609,224,-609,609,-224,609,-224,224,-609,224,-609,609,-224,609,-224,609,-224,224,-609,609,-224,224,-609,224,-609,224]
      - light.turn_off: onboard_led
    turn_off_action:
      - light.turn_on: onboard_led
      - remote_transmitter.transmit_raw:
          transmitter_id: tx_315
          repeat:
            times: 10
            wait_time: 6ms
          code: [609,-224,224,-609,609,-224,224,-609,609,-224,609,-224,609,-224,224,-609,224,-609,609,-224,609,-224,224,-609,224,-609,609,-224,609,-224,224,-609,224,-609,609,-224,609,-224,609,-224,224,-609,609,-224,224,-609,609,-224,224]
      - light.turn_off: onboard_led
