substitutions:
  name: sht30-11
  id_prefix: sht30_11
  friendly_name: "SHT30 11"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp8266:  
  board: d1_mini

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base.yaml
  esp8266vcc_adc: !include common/esp8266vcc_adc.yaml
  sht30_base: !include common/sht30_base.yaml
