substitutions:
  name: sht30_01

esphome:
  name: ${name}
  platform: ESP8266
  board: d1_mini

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base.yaml
  esp8266vcc_adc: !include common/esp8266vcc_adc.yaml
  mqtt: !include common/mqtt.yaml

mqtt:
  on_message:
    - topic: esphome/${name}/ota_mode
      payload: 'ON'
      then:
        - deep_sleep.prevent: deep_sleep_1
    - topic: esphome/${name}/ota_mode
      payload: 'OFF'
      then:
        - deep_sleep.allow: deep_sleep_1

ota:
  on_begin:
    then:
      - deep_sleep.prevent: deep_sleep_1
  on_end:
    then:
      - deep_sleep.allow: deep_sleep_1

deep_sleep:
  run_duration: 60s
  sleep_duration: 5min
  id: deep_sleep_1

i2c:
  sda: GPIO4
  scl: GPIO5

sensor:
  - platform: sht3xd
    address: 0x45
    temperature:
      name: "${name} Temperature"
      unit_of_measurement: "°F"
      filters:
        - lambda: return x * (9.0/5.0) + 32.0; # convert to °F
        - multiply: 0.9876
        - offset: 0.397
    humidity:
      name: "${name} Humidity"
      filters:
        - multiply: 0.9686
        - offset: 3.785
      on_value:
        then:
          - delay: 10s
          - deep_sleep.enter:
              id: deep_sleep_1
              sleep_duration: 5min