substitutions:
  name: upstairs_aq

esphome:
  name: ${name}
  platform: ESP8266
  board: nodemcuv2

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base.yaml

i2c:
  sda: D2
  scl: D1
  scan: true
  #id: bus_a

sensor:

## Pocket Geiger Radiation Sensor - Type 5
  - platform: pulse_counter
    pin:
      number: D5
      mode:
        input: true
        pullup: true
    name: "${name} Radiation CPM"
    id: "${name}_radiation_cpm"
    unit_of_measurement: "cpm"
    icon: "mdi:radioactive"
    count_mode:
      rising_edge: DISABLE
      falling_edge: INCREMENT
    #internal_filter: 13us
    update_interval: 120s
    accuracy_decimals: 1
    total:
      name: "${name} Total Radiation Counts"
      unit_of_measurement: "counts"
      icon: "mdi:radioactive"
      accuracy_decimals: 0

  - platform: template
    name: "${name} Radiation Dose Rate"
    unit_of_measurement: "µS/hr"
    icon: "mdi:radioactive"
    accuracy_decimals: 2
    lambda: |-
      return id(${name}_radiation_cpm).state * 0.08;

  - platform: pulse_counter
    pin:
      number: D6
      mode:
        input: true
        pullup: true
    name: "${name} Noise CPM"
    id: "${name}_noise_cpm"
    unit_of_measurement: "cpm"
    icon: "mdi:bell-alert"
    count_mode:
      rising_edge: DISABLE
      falling_edge: INCREMENT
    #internal_filter: 13us
    update_interval: 60s
    accuracy_decimals: 1
    total:
      name: "${name} Total Noise Counts"
      unit_of_measurement: "counts"
      icon: "mdi:bell-alert"
      accuracy_decimals: 0

## SCD30 CO2 sensor
  - platform: scd30
    co2:
      name: "${name} NDIR CO2"
      accuracy_decimals: 0
    temperature:
      name: "${name} Temperature"
      id: "${name}_temperature"
      accuracy_decimals: 1
    humidity:
      name: "${name} Humidity"
      id: "${name}_humidity"
      accuracy_decimals: 0
    #temperature_offset: 1.5 °C
    automatic_self_calibration: true
    #ambient_pressure_compensation: 800
    altitude_compensation: 1829m
    address: 0x61
    update_interval: 60s

## Particulate Matter Sensor - SPS30
  - platform: sps30
    pm_1_0:
      name: "${name} PM <1µm Mass concentration"
      id: "${name}_PM_1_0"
    pm_2_5:
      name: "${name} PM <2.5µm Mass concentration"
      id: "${name}_PM_2_5"
    pm_4_0:
      name: "${name} PM <4µm Mass concentration"
      id: "${name}_PM_4_0"
    pm_10_0:
      name: "${name} PM <10µm Mass concentration"
      id: "${name}_PM_10_0"
    pmc_0_5:
      name: "${name} PM <0.5µm Number concentration"
      id: "${name}_PMC_0_5"
    pmc_1_0:
      name: "${name} PM <1µm Number concentration"
      id: "${name}_PMC_1_0"
    pmc_2_5:
      name: "${name} PM <2.5µm Number concentration"
      id: "${name}_PMC_2_5"
    pmc_4_0:
      name: "${name} PM <4µm Number concentration"
      id: "${name}_PMC_4_0"
    pmc_10_0:
      name: "${name} PM <10µm Number concentration"
      id: "${name}_PMC_10_0"
    address: 0x69
    update_interval: 60s

## CCS811 TVOC sensor

  - platform: ccs811
    eco2:
      name: "${name} eCO2"
    tvoc:
      name: "${name} TVOC"
    address: 0x5A
    temperature: "${name}_temperature"
    humidity: "${name}_humidity"
    update_interval: 60s