substitutions:
  name: water_heater

esphome:
  name: ${name}
  platform: ESP8266
  board: d1_mini

packages:
  wifi: !include common/wifi.yaml
  web_server: !include common/web_server.yaml
  device_base: !include common/device_base.yaml
  esp8266vcc_adc: !include common/esp8266vcc_adc.yaml

sensor:
  - platform: pulse_counter
    pin:
      number: D5
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Water Heater Controller LED CPM"
    id: water_heater_controller_led_cpm
    unit_of_measurement: "cpm"
    icon: "mdi:led-on"
    count_mode:
      rising_edge: DISABLE
      falling_edge: INCREMENT
    internal_filter: 50ms
    update_interval: 30s # report every 30 s
    accuracy_decimals: 0
    on_value:
      - if:
          condition:
            sensor.in_range:
              id: water_heater_controller_led_cpm
              below: 5
          then:
            - binary_sensor.template.publish:
                id: water_heater_power
                state: OFF
            - binary_sensor.template.publish:
                id: water_heater_error
                state: ON
      - if:
          condition:
            sensor.in_range:
              id: water_heater_controller_led_cpm
              above: 5
              below: 35
          then:
            - binary_sensor.template.publish:
                id: water_heater_power
                state: ON
            - binary_sensor.template.publish:
                id: water_heater_error
                state: OFF
      - if:
          condition:
            sensor.in_range:
              id: water_heater_controller_led_cpm
              above: 35
          then:
            - binary_sensor.template.publish:
                id: water_heater_power
                state: ON
            - binary_sensor.template.publish:
                id: water_heater_error
                state: ON
            
binary_sensor:
  - platform: template
    device_class: power
    name: "Water Heater Power"
    id: "water_heater_power"

  - platform: template
    device_class: problem
    name: "Water Heater Error"
    id: "water_heater_error"