substitutions:
  name: water-heater-01
  id_prefix: water_heater_01
  friendly_name: "Water Heater 01"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: lolin_c3_mini
  framework:
    type: esp-idf

packages:
  wifi: !include common/wifi.yaml
  web_server: !include common/web_server.yaml
  device_base: !include common/device_base.yaml
  chip_temp: !include common/chip_temp.yaml

wifi:
  output_power: 11dBm # decrease to enable connection

# Enable logging
logger:
  level: DEBUG
  logs:
    sensor: INFO
    dallas.temp.sensor: INFO

one_wire:
  - platform: gpio
    pin: GPIO8

sensor:
  - platform: dallas_temp
    address: 0x5e000000bab8cf28
    resolution: 11  # 0.125°C precision
    name: "Water Temperature"
    id: ${id_prefix}_temperature
    unit_of_measurement: "°C" # keep all internal values in °C, convert to °F in Home Assistant if needed
    update_interval: 1s
    filters:
      - median:
          window_size: 10
          send_every: 1
          send_first_at: 1
      - exponential_moving_average:
          alpha: 0.2
          send_every: 15

  # Water Pressure Sensor (using ADC)
  - platform: adc
    pin: GPIO3
    attenuation: 0db
    name: "Water Pressure Raw Voltage"
    id: ${id_prefix}_water_pressure_raw_voltage
    unit_of_measurement: "V"
    accuracy_decimals: 3
    samples: 5
    update_interval: 500ms
    filters:
      - median:
          window_size: 10
          send_every: 1
          send_first_at: 1
      - exponential_moving_average:
          alpha: 0.2
          send_every: 15
      - delta: 0.25%

  - platform: template
    name: "Water Pressure"
    id: ${id_prefix}_water_pressure
    unit_of_measurement: "psi"
    icon: "mdi:gauge"
    accuracy_decimals: 1
    update_interval: 500ms
    lambda: |-
      return id(${id_prefix}_water_pressure_raw_voltage).state;
    # https://docs.google.com/spreadsheets/d/1oPyy6xiM6HDB5ek-y8KKNhnjfx7NZcLlSu-kK-Rz0oE/edit?usp=sharing
    filters:
      - multiply: 119
      - offset: -21.7
      - clamp:
          min_value: 0.0
      - delta: 0.25%
      - heartbeat:
          period: 60s
          optimistic: true
