substitutions:
  name: water-heater
  id_prefix: water_heater
  friendly_name: "Water Heater"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp8266:
  board: d1_mini

packages:
  wifi: !include common/wifi.yaml
  web_server: !include common/web_server.yaml
  device_base: !include common/device_base.yaml
  esp8266vcc_adc: !include common/esp8266vcc_adc.yaml

sensor:
  - platform: pulse_counter
    pin:
      number: D5
      inverted: true
      mode:
        input: true
        pullup: true
    name: "LED CPM"
    id: ${id_prefix}_led_cpm
    unit_of_measurement: "cpm"
    icon: "mdi:led-on"
    count_mode:
      rising_edge: DISABLE
      falling_edge: INCREMENT
    internal_filter: 50ms
    update_interval: 30s # report every 30 s
    accuracy_decimals: 0
    on_value:
      - if:
          condition:
            sensor.in_range:
              id: ${id_prefix}_led_cpm
              below: 5
          then:
            - binary_sensor.template.publish:
                id: ${id_prefix}_power
                state: OFF
            - binary_sensor.template.publish:
                id: ${id_prefix}_error
                state: ON
      - if:
          condition:
            sensor.in_range:
              id: ${id_prefix}_led_cpm
              above: 5
              below: 35
          then:
            - binary_sensor.template.publish:
                id: ${id_prefix}_power
                state: ON
            - binary_sensor.template.publish:
                id: ${id_prefix}_error
                state: OFF
      - if:
          condition:
            sensor.in_range:
              id: ${id_prefix}_led_cpm
              above: 35
          then:
            - binary_sensor.template.publish:
                id: ${id_prefix}_power
                state: ON
            - binary_sensor.template.publish:
                id: ${id_prefix}_error
                state: ON
            
binary_sensor:
  - platform: template
    device_class: power
    name: "Power"
    id: ${id_prefix}_power

  - platform: template
    device_class: problem
    name: "Error"
    id: ${id_prefix}_error