# https://esphome.io/components/sensor/internal_temperature.html
# The internal_temperature sensor platform allows you to use the 
# integrated temperature sensor of the ESP32, RP2040 and BK72XX chip.
sensor:
  - platform: internal_temperature
    name: "${name} Chip Temperature"
    update_interval: 60s
    accuracy_decimals: 1
    