# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret hass_api_password

ota:
  - platform: esphome
    password: !secret ota_password

sensor:
  - platform: uptime
    name: "Uptime"
    id: ${id_prefix}_uptime

text_sensor:
  - platform: version
    name: "ESPHome Version"
    id: ${id_prefix}_esphome_version

button:
  - platform: restart
    name: "Restart Node"
    id: ${id_prefix}_restart_button
    disabled_by_default: True
    icon: "mdi:restart"

  - platform: safe_mode
    name: "Restart Node (Safe Mode)"
    id: ${id_prefix}_restart_safe_mode
    disabled_by_default: True
