# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret hass_api_password

ota:
  password: !secret ota_password

#mqtt:
#  broker: !secret mqtt_broker

#web_server:

sensor:
  - platform: uptime
    name: "${name} Uptime"
    id: "${name}_uptime"

text_sensor:
  - platform: version
    name: "${name} ESPHome Version"

button:
  - platform: restart
    id: restart_button
    name: "${name} Restart Node"
    disabled_by_default: True
    icon: "mdi:restart"