# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret hass_api_password

ota:
  password: !secret ota_password

#mqtt:
#  broker: !secret mqtt_broker

web_server:

sensor:
  - platform: uptime
    name: "${name} Uptime"