### pins ###
# D1 GPIO5  | LED blue    | status_led
# D0 GPIO16 | LED yellow  | led_yellow
# D5 GPIO14 | SW1         | button
# D2 GPIO4  | REL1        | relay
# D6 GPIO12 | HLW8012/CF1 | cf1_pin
# D7 GPIO13 | HLW8012/CF  | cf_pin

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp8266:
  board: esp12e

packages:
  wifi: !include wifi.yaml
  device_base: !include device_base.yaml

binary_sensor:
  - platform: gpio
    id: ${id_prefix}_button
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      then:
        - switch.toggle: ${id_prefix}_relay

status_led:
  pin:
    number: GPIO5

output:
  - platform: gpio
    id: ${id_prefix}_led_yellow
    pin: GPIO16

switch:
  - platform: gpio
    name: "Relay"
    id: ${id_prefix}_relay
    pin: GPIO4
    icon: "mdi:power-plug"
    restore_mode: RESTORE_DEFAULT_ON
    on_turn_on:
      - output.turn_on: ${id_prefix}_led_yellow
    on_turn_off:
      - output.turn_off: ${id_prefix}_led_yellow

sensor:
  - platform: hlw8012
    sel_pin: GPIO15
    cf_pin: GPIO13
    cf1_pin: GPIO12
    # current_resistor: 0.002
    # voltage_divider: 2351
    # current:
    #   name: "Current"
    #   id: ${id_prefix}_current
    #   unit_of_measurement: A
    #   accuracy_decimals: 3
    voltage:
      name: "Voltage"
      id: ${id_prefix}_voltage
      unit_of_measurement: V
      accuracy_decimals: 1
    power:
      name: "Power"
      id: ${id_prefix}_power
      unit_of_measurement: W
      accuracy_decimals: 1
      on_value:
        - sensor.template.publish:
            id: ${id_prefix}_current
            state: !lambda return id(${id_prefix}_power).state / id(${id_prefix}_voltage).state;
    update_interval: 10s
    initial_mode: VOLTAGE
    change_mode_every: 4294967295 # basically never
  - platform: template
    name: "Current"
    id: ${id_prefix}_current
    unit_of_measurement: A
    accuracy_decimals: 2
    