# https://www.esphome-devices.com/devices/Sonoff-S31

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp8266:
  board: esp12e
  restore_from_flash: true # save some values to flash
  early_pin_init: true # default

packages:
  wifi: !include wifi.yaml
  device_base: !include device_base.yaml
  esp8266vcc_adc: !include esp8266vcc_adc.yaml

logger:
  baud_rate: 0 # (UART logging interferes with cse7766 sensor)

uart:
  rx_pin: RX
  baud_rate: 4800

status_led:
  pin: 
    number: GPIO13
    inverted: False # LED is Active low. Don't use inverted so that LED is default on when no error - for power indication

number:
  - platform: template
    name: "Connected Device Power Threshold"
    id: ${id_prefix}_connected_device_power_threshold
    disabled_by_default: true
    optimistic: true
    min_value: 0
    max_value: 2000
    step: 1
    restore_value: true
    initial_value: 10

  - platform: template
    name: "Button Lockout Time"
    id: ${id_prefix}_button_lockout_time
    disabled_by_default: true
    optimistic: true
    min_value: 0
    max_value: 5000
    step: 100
    restore_value: true
    initial_value: 100

binary_sensor:
  - platform: gpio
    name: "Button"
    id: ${id_prefix}_button
    internal: True
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    filters:
      delayed_off: !lambda return id(${id_prefix}_button_lockout_time).state;
    on_press:
      if:
        condition:
          switch.is_off: ${id_prefix}_disable_button
        then:
          - switch.toggle: ${id_prefix}_relay
        else:
          - logger.log:
              format: "Physical button pressed, but it is disabled via software setting."
              level: INFO
  
  - platform: template
    name: "Connected Device Status"
    id: ${id_prefix}_connected_device_status
    disabled_by_default: True
    device_class: running
    lambda: |-
      if (id(${id_prefix}_power).state > id(${id_prefix}_connected_device_power_threshold).state) {
        // Device is on.
        return true;
      } else {
        // Device is off.
        return false;
      }

button:
  # on-plug action to power cycle the connected device
  - platform: template
    name: "Restart Connected"
    id: ${id_prefix}_restart_connected
    disabled_by_default: True
    icon: "mdi:restart-alert"
    on_press:
      then: 
        - switch.turn_off: ${id_prefix}_relay
        - delay: 5s
        - switch.turn_on: ${id_prefix}_relay

switch:
  - platform: gpio
    name: "Relay"
    id: ${id_prefix}_relay
    pin: GPIO12
    icon: "mdi:power-plug"
    restore_mode: RESTORE_DEFAULT_ON

  - platform: template
    name: "Disable Button"
    id: ${id_prefix}_disable_button
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    disabled_by_default: True

sensor:
  - platform: cse7766
    current:
      name: "Current"
      id: ${id_prefix}_current
      accuracy_decimals: 2
      icon: "mdi:current-ac"
      filters:
        - throttle_average: 10s
    voltage:
      name: "Voltage"
      id: ${id_prefix}_voltage
      accuracy_decimals: 1
      filters:
        - throttle_average: 10s
    power:
      name: "Power"
      id: ${id_prefix}_power
      icon: "mdi:lightning-bolt-circle"
      accuracy_decimals: 2
      filters:
        - throttle_average: 10s
        - lambda: |-
            if (id(${id_prefix}_relay).state) {
              return x;   
            } else {
              return 0;
            }
    energy:
      name: "Energy"
      id: ${id_prefix}_energy
      state_class: total_increasing
      device_class: energy
      accuracy_decimals: 3
      unit_of_measurement: 'kWh'
      filters:
        - throttle_average: 10s
        # Multiplication factor from W to kW is 0.001
        - multiply: 0.001
    apparent_power:
      name: "Apparent Power"
      id: ${id_prefix}_apparent_power
      icon: "mdi:lightning-bolt-circle"
      accuracy_decimals: 2
      filters:
        - throttle_average: 10s
        - lambda: |-
            if (id(${id_prefix}_relay).state) {
              return x;   
            } else {
              return 0;
            }
    power_factor:
      name: "Power Factor"
      id: ${id_prefix}_power_factor
      accuracy_decimals: 2
      filters:
        - throttle_average: 10s

  - platform: total_daily_energy
    name: "Total Daily Energy"
    id: ${id_prefix}_total_daily_energy
    power_id: ${id_prefix}_power
    unit_of_measurement: 'kWh'
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001

# Enable time component to reset energy at midnight
time:
  - platform: homeassistant
    id: homeassistant_time
