# https://www.esphome-devices.com/devices/Sonoff-S31

packages:
  esp8266vcc_adc: !include esp8266vcc_adc.yaml

logger:
  baud_rate: 0 # (UART logging interferes with cse7766)

uart:
  rx_pin: RX
  baud_rate: 4800

status_led:
  pin: GPIO13

binary_sensor:
  - platform: gpio
    name: ${name} Button
    internal: True
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: relay
  - platform: template
    name: ${name} Connected Device Status
    disabled_by_default: True
    device_class: power
    lambda: |-
      if (id(cse7766_power).state > id(connected_device_power_threshold)) {
        // Device is on.
        return true;
      } else {
        // Device is off.
        return false;
      }

button:
  # on-plug action to power cycle the connected device
  - platform: template
    name: ${name} Restart Connected
    disabled_by_default: True
    icon: "mdi:restart-alert"
    on_press:
      then: 
        - switch.turn_off: relay
        - delay: 10s
        - switch.turn_on: relay

switch:
  - platform: gpio
    name: ${name} Relay
    pin: GPIO12
    id: relay
    icon: "mdi:power-plug"
    restore_mode: RESTORE_DEFAULT_ON

sensor:
  - platform: cse7766
    update_interval: 10s
    current:
      name: ${name} Current
      accuracy_decimals: 2
      icon: "mdi:current-ac"
    voltage:
      name: "${name} Voltage"
      accuracy_decimals: 1
    power:
      icon: "mdi:lightning-bolt-circle"
      name: ${name} Power
      id: cse7766_power
      accuracy_decimals: 2
      filters:
        - lambda:
            if (id(relay).state) {
              return x;   
            } else {
              return 0;
            }

  - platform: total_daily_energy
    name: '${name} Total Daily Energy'
    power_id: cse7766_power
    unit_of_measurement: 'kWh'
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001

# Enable time component to reset energy at midnight
time:
  - platform: homeassistant
    id: homeassistant_time