mqtt:
  broker: !secret mqtt_broker
  discovery: false
  topic_prefix: null # don't publish mqtt messages
  on_message:
    - topic: esphome/${name}/ota_mode
      payload: 'ON'
      then:
        - deep_sleep.prevent: ${id_prefix}_deep_sleep
    - topic: esphome/${name}/ota_mode
      payload: 'OFF'
      then:
        - deep_sleep.allow: ${id_prefix}_deep_sleep

ota:
  - id: !extend ${id_prefix}_ota
    on_begin:
      then:
        - deep_sleep.prevent: ${id_prefix}_deep_sleep
    on_end:
      then:
        - deep_sleep.allow: ${id_prefix}_deep_sleep

deep_sleep:
  run_duration: 60s
  sleep_duration: 5min
  id: ${id_prefix}_deep_sleep

i2c:
  sda: GPIO4
  scl: GPIO5

sensor:
  - platform: sht3xd
    address: 0x45
    temperature:
      name: "Temperature"
      id: ${id_prefix}_temperature
      unit_of_measurement: "°F"
      filters:
        - lambda: return x * (9.0/5.0) + 32.0; # convert to °F
        - multiply: 0.9876
        - offset: 0.397
    humidity:
      name: "Humidity"
      id: ${id_prefix}_humidity
      filters:
        - multiply: 0.9686
        - offset: 3.785
      on_value:
        then:
          - delay: 10s
          - deep_sleep.enter:
              id: ${id_prefix}_deep_sleep
              sleep_duration: 5min
              