wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain
  fast_connect: true
  min_auth_mode: WPA2 # don't use WPA

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Hotspot"
    password: !secret wifi_password

captive_portal:

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    id: ${id_prefix}_wifi_signal
    update_interval: 60s
